version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
  build:
    commands:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug assembleDebugAndroidTest
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
    - app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  discard-paths: yes